# name: Deploy Node.js App to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.EC2_KEY }}  # 🟢 using your secret here

#       - name: Deploy to EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no ubuntu@3.87.75.136 << 'EOF'
#             cd ~/wwah_backend
#             git pull origin main
#             npm install
#             pm2 restart my-backend || pm2 start server.js --name my-backend
#           EOF
name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -tt -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=60 \
              -o ServerAliveCountMax=5 \
              ubuntu@3.87.75.136 << 'EOF'
            set -e  # exit immediately if any command fails

            echo "🔹 Navigating to project directory..."
            cd ~/wwah_backend

            echo "🔹 Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "🔹 Installing dependencies..."
            npm install --production

            echo "🔹 Restarting PM2 process..."
            pm2 restart my-backend || pm2 start server.js --name my-backend

            echo "✅ Deployment complete!"
          EOF
