name: Deploy to EC2

on:
  push:
    branches:
      - feature/gitflows

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Debug Key
        run: |
          head -n 2 key.pem

      - name: Deploy to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@"${{ secrets.EC2_IP }}" << 'EOF'
          export NVM_DIR="/home/ubuntu/.nvm"
          export PATH="$NVM_DIR/versions/node/v20.18.3/bin:$PATH"

          echo "PATH: $PATH"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "PM2 version: $(pm2 -v)"

            # Move to /home/ubuntu
            cd /home/ubuntu

            # Create a new directory for the project (e.g., "wwah_backend")
            mkdir -p wwah_backend

            # Change to the new directory
            cd wwah_backend

            # Clone the repo if it doesn't exist
            if [ ! -d ".git" ]; then
              git clone https://github.com/HMZain007/wwah_backend.git .
            fi

            # Pull latest changes from the main branch
            git pull origin main

            echo "Creating or overwriting the .env file"
            cat << 'EOF' > .env
            NODE_ENV=production
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            PORT=8080
            EOF

            # Install dependencies
            npm install

            # Restart or start the app with PM2
            pm2 restart wwah_backend || pm2 start server.js --name wwah_backend
          EOF
